name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: npm ci
    - name: Build project
      run: npm run build
    - name: Lint code
      run: npm run lint
    - name: Test project
      run: npm test
    - name: Deploy to GitHub Pages
      run: npm run deploy
